apiVersion : apps/v1
kind: Deployment
metadata:
  name: "devopsclusteraks-c4c8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "devopsclusteraks-c4c8"
  template:
    metadata:
      labels:
        app: "devopsclusteraks-c4c8"
    spec:
      containers:
        - name: "devopsclusteraks-c4c8"
          image: "myacr4568975.azurecr.io/go"
          ports:
          - containerPort: 80
