apiVersion: v1
kind: Service
metadata:
    name: "devopsclusteraks-3849"
    labels:
        app: "devopsclusteraks-3849"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "devopsclusteraks-3849"