apiVersion: v1
kind: Service
metadata:
    name: "devopsclusteraks-0541"
    labels:
        app: "devopsclusteraks-0541"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "devopsclusteraks-0541"