name: Workflow Go-application
on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
       envPAT:
          required: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacr4568975.azurecr.io
        username: ${{ secrets.acr_myacr4568975_username }}
        password: ${{ secrets.acr_myacr4568975_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/website" -f  "website/Dockerfile" -t myacr4568975.azurecr.io/devopsclusteraks:${{ github.sha }} --label dockerfile-path=website/Dockerfile
        docker push myacr4568975.azurecr.io/devopsclusteraks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep namespace-go-app | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace namespace-go-app`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: namespace-go-app
        container-registry-url: myacr4568975.azurecr.io
        container-registry-username: ${{ secrets.acr_myacr4568975_username }}
        container-registry-password: ${{ secrets.acr_myacr4568975_password }}
        secret-name: devopsclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: namespace-go-app
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myacr4568975.azurecr.io/devopsclusteraks:${{ github.sha }}
        imagepullsecrets: |
          devopsclustedockerauth
