name: Workflow Main
on: workflow_call
  secrets:
         registry_username:
            required: true
         registry_password:
            required: true
jobs:
  credentials-job:
    name: Pass input and secrets to main.yml
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/main.yml
      with:
         username: ${{ inputs.username }}
         token: ${{ secrets.token }} 

    - uses: WoutBeyens/CICDaas/action.yaml@v2
      with:
        type: 'Go'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: goDeployment
        serviceManifest: goService

    - uses: WoutBeyens/CICDaas/action.yaml@v2
      with:
        type: 'Php'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: phpDeployment
        serviceManifest: phpService

    - uses: WoutBeyens/CICDaas/action.yaml@v2
      with:
        type: 'Dotnet'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: dotnetDeployment
        serviceManifest: dotnetService
