name: Workflow Main
on: workflow_dispatch
 
jobs:
  build-correct-application:
    name: Build correct application based on input (programming language)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: WoutBeyens/CICDaas@v13
      with:
        type: 'go'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: goDeployment
        serviceManifest: goService
        namespace: goNamespace

    - uses: WoutBeyens/CICDaas@v13
      with:
        type: 'php'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: phpDeployment
        serviceManifest: phpService
        namespace: phpNamespace

    - uses: WoutBeyens/CICDaas@v13
      with:
        type: 'dotnet'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: dotnetDeployment
        serviceManifest: dotnetService
        namespace: dotnetNamespace
     
    - name: Run Trivy vulnerability scanner in repo mode
      uses: WoutBeyens/CICDaas@v13
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

