name: Workflow Main
on: workflow_call
 
jobs:
  build-correct-application:
    name: Build correct application based on input (programming language)
    runs-on: ubuntu-latest
    steps:
    - uses: WoutBeyens/CICDaas/action.yaml@v2
      with:
        type: 'Go'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: goDeployment
        serviceManifest: goService

    - uses: WoutBeyens/CICDaas/action.yaml@v2
      with:
        type: 'Php'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: phpDeployment
        serviceManifest: phpService

    - uses: WoutBeyens/CICDaas/action.yaml@v2
      with:
        type: 'Dotnet'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: dotnetDeployment
        serviceManifest: dotnetService
