name: Workflow Main
on: workflow_dispatch
 
jobs:
  build-correct-application:
    name: Build correct application based on input (programming language)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go-application
      uses: WoutBeyens/CICDaas@v14
      with:
        type: 'go'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: goDeployment
        serviceManifest: goService
        namespace: goNamespace

    - name: Build PHP-application
      uses: WoutBeyens/CICDaas@v14
      with:
        type: 'php'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: phpDeployment
        serviceManifest: phpService
        namespace: phpNamespace

    - name: Build .NET application
      uses: WoutBeyens/CICDaas@v14
      with:
        type: 'dotnet'
        dockerUsername: ${{ secrets.acr_myacr4568975_username }}
        dockerPassword: ${{ secrets.acr_myacr4568975_password }}
        kubeConfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
        deploymentManifest: dotnetDeployment
        serviceManifest: dotnetService
        namespace: dotnetNamespace



