name: Caller Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
   # Inputs the workflow accepts.
    inputs:
      buildDifferentApp:
        # Friendly description to be shown in the UI instead of 'name'.
        description: 'Which programming language?'
        # Default value if no value is explicitly provided
        default: 'Go'
        # Input has to be provided for the worflow to run.
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildDifferentAppPlatform:
    if: ${{ github.event.inputs.buildDifferentApp == 'Go' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    uses: ./.github/workflows/deploytoAksCluster.yml
    
  call-workflow-passing-data:
    uses: ./.github/workflows/deploytoAksCluster.yml
    with:
      username: WoutBeyens
    secrets: inherit
